### ISSUE TITLE
Request of indigo release 

### ISSUE THREAD

**Issue by garaemon** [PR2/pr2_ethercat_drivers#68]
Could you release deb of this package on indigo?

**Comment by UltronDestroyer** [comment]
I can try, but it has lots of dependencies, so we will see if that is possible at this exact moment.

**Comment by garaemon** [comment]
thanks! I think eml package is not available on indigo...

**Comment by UltronDestroyer** [comment]
I don't think eml is required. It used to be, but does it provide any value?

**Comment by UltronDestroyer** [comment]
Requires pr2_common, I've included eml in the indigo release.

**Comment by trainman419** [comment]
EML is the EtherCat Master Library - definitely required as a dependency for releasing the pr2 ethercat drivers.

The ROS package was maintained as part of the PR2 software in the past; you should have release rights for it. If you can't figure out how to release it, let me know and I'll take a deeper look.

**Comment by UltronDestroyer** [comment]
It was on the groovy branch on this repo and I catkinized it and released it into indigo. I don't believe the deb built tho.. So I'll see what's up with it.

**Comment by trainman419** [comment]
EML shouldn't be catkinized; it should be released as a third-party package. That's why it was removed from the hydro branch.

**Comment by UltronDestroyer** [comment]
Ohh I see what you mean now. Theres the eml package with the patch, but he actual .so needs to be released too, yeah?

**Comment by trainman419** [comment]
The release repo for EML is: https://github.com/ros-gbp/eml-release

The [tracks.yaml](https://github.com/ros-gbp/eml-release/blob/master/tracks.yaml) specifies that the source should be downloaded from pr.willowgarage.com, patched with the included package.xml, and then built into a deb on the farm.

Since pr.willowgarage.com no longer exists, I've uploaded the source tarball to my server: http://namniart.com/eml-r36.tar.gz . Please host it somewhere else and update the tacks.yaml in release repo accordingly.

Once you have the source hosted in a new location, and the tracks.yaml updated, you should re-release the current version in hydro; confirm that it works, and then create a new release track for the indigo release and run the bloom release for indigo.

**Comment by trainman419** [comment]
@TheDash really? you forked the groovy-devel branch to create the Indigo release, and potentially discarded all of the patches and fixes that went into Hydro? that's a great way to ruin the version history of a repository and make it very difficult to keep track of changes.

I suspect the changes  between Hydro and Indigo are so small that you don't even need to maintain a separate indigo-devel branch, assuming that you actually release the eml package properly.

In the future, you should check the debbuild page and the rosdistro index before assuming that a package was removed for Hydro; there were a significant number of PR2-related packages that I migrated to third-party packages for the Hydro release.

**Comment by UltronDestroyer** [comment]
My main intent with that was to get the other pr2 packages released into the distribution yaml, some others had been requiring it for their releases, and I hadn't really looked into whether the contents were achieving anything yet. That was the quickest way to do it with the resources I had. Pretty sure I didn't understand what was going on with the eml situation.

Are you saying that the indigo devel branch is unnecessary? I'm convinced that its convention to create a source branch w.r.t the rosversion its for.

I understand what you mean now. Eml was supposed to be released as third party but is now released under ethercat drivers. 

Is this going to cause issues with indigo, or can it be fixed by pointing the source of eml to the new location?

**Comment by UltronDestroyer** [comment]
Oh wait what, I see what you mean by skipping hydro. I am pretty sure users can just look at the hydro branch to see the commits made from there. The changes aren't lost. They just aren't merged into one stream.

**Comment by trainman419** [comment]
EML was an old, third-party package which built primarily using special rosbuild Makefile targets; not the CMakeLists (go read the Makefile). These targets aren't supported by catkin, and is why I converted it into a third-party package.

You should delete the indigo-devel branch, remove the releases you've made from rosdistro, and start over. Release the third-party version of EML into Indigo, verify that it builds, and then install the eml deb and verify that the hydro-devel branch builds on indigo. Once you've confirmed that, _then_ you can release the hydro-devel branch into Indigo.

**Comment by UltronDestroyer** [comment]
Gotcha. EML first, and then pr2_ethercat_drivers.

On Thu, Jan 15, 2015 at 11:33 PM, Austin notifications@github.com wrote:

> EML was an old, third-party package which built primarily using special
> rosbuild Makefile targets; not the CMakeLists (go read the Makefile). These
> targets aren't supported by catkin, and is why I converted it into a
> third-party package.
> 
> You should delete the indigo-devel branch, remove the releases you've made
> from rosdistro, and start over. Release the third-party version of EML into
> Indigo, verify that it builds, and then install the eml deb and verify that
> the hydro-devel branch builds on indigo. Once you've confirmed that,
> _then_ you can release the hydro-devel branch into Indigo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PR2/pr2_ethercat_drivers/issues/68#issuecomment-70207180
> .

## 

Devon Ash
<a href="http://ca.linkedin.com/pub/devon-ash/48/478/981"
style="text-decoration:none;"><span style="font: 80% Arial,sans-serif;
color:#0783B6;"><img src="
https://static.licdn.com/scds/common/u/img/webpromo/btn_in_20x15.png"
width="20" height="15" alt="View Devon Ash's LinkedIn profile"
style="vertical-align:middle" border="0">View Devon Ash's profile</span></a>

**Comment by garaemon** [comment]
http://jenkins.ros.org/view/IbinS32/job/ros-indigo-eml_binarydeb_saucy_i386/20/console

Still failing to build EML. any update?

**Comment by UltronDestroyer** [comment]
That's right, I haven't had a chance to do the fix Austin mentioned. Tomorrow though, I'll be scheduled to get it started. We've just received a new set of servers from WG, and I was trying to put 14.04 on them in the past week.

**Comment by garaemon** [comment]
Thanks!

**Comment by UltronDestroyer** [comment]
Thoughts on this @ahendrix? https://github.com/shadow-robot/ros_ethercat
